### ISSUE TITLE
GetPackMeasurements (

### ISSUE THREAD

**Issue by tobydavies11** [maland16/daly-bms-uart#14]
Trying to use the advanced example for the below but it’s failing as not recognised.

has the library been altered, and the example not updated?
 
 bms.getPackMeasurements(volts, amps, percentage);

**Comment by softwarecrash** [comment]
yes its altered
the commands like there
  Serial.println("basic BMS Data:              " + (String)bms.get.packVoltage + "V " + (String)bms.get.packCurrent + "I " + (String)bms.get.packSOC + "\% ");
  Serial.println("Package Temperature:         " + (String)bms.get.tempAverage);
  Serial.println("Highest Cell Voltage Nr:     " + (String)bms.get.maxCellVNum + " with voltage " + (String)(bms.get.maxCellmV / 1000));
  Serial.println("Lowest Cell Voltage Nr:      " + (String)bms.get.minCellVNum + " with voltage " + (String)(bms.get.minCellmV / 1000));
  Serial.println("Number of Cells:             " + (String)bms.get.numberOfCells);
  Serial.println("Number of Temp Sensors:      " + (String)bms.get.numOfTempSensors);
  Serial.println("BMS Chrg / Dischrg Cycles:   " + (String)bms.get.bmsCycles);
  Serial.println("BMS Heartbeat:               " + (String)bms.get.bmsHeartBeat); // cycle 0-255
  Serial.println("Discharge MOSFet Status:     " + (String)bms.get.disChargeFetState);
  Serial.println("Charge MOSFet Status:        " + (String)bms.get.chargeFetState);
  Serial.println("Remaining Capacity mAh:      " + (String)bms.get.resCapacitymAh);
  
  take a look in the files, most is descripted

**Comment by maland16** [comment]
Rocky addressed this, closing
