### ISSUE TITLE
convert to softwareservial

### ISSUE THREAD

**Issue by softwarecrash** [maland16/daly-bms-uart#17]
hey @maland16 i need a little bit help from you
i will try to rewrite it to use softwareserial but i dont know to do it

**Comment by maland16** [comment]
I'm pretty busy right now and don't have a ton of time to help, but I encourage you to take a shot at it! I wish I had more time to devote to this project, and I truly appreciate your contributions!

**Comment by softwarecrash** [comment]
Thanks for your replay.
So i noticed that softwareserial Not will Work Stabel, so this Idea going to Trash.
Later i will make a PR with a little Changes and a new function, when you find the time please add it.
