### ISSUE TITLE
'Serial1' was not declared in this scope

### ISSUE THREAD

**Issue by PRADIPMAHAJAN** [maland16/daly-bms-uart#2]
Hello Sir, I need your help, I have one issue with my BMS. When I compile your code after including #include <daly-bms-uart.h> it is also add in my manage library. It shows the error 'Serial1' was not declared in this scope. and I noticed here you are used printf function in Arduino. I want to connect my Daly BMS with the ESP8266 for getting the data from BMS. I tried getting the data from BMS using Python code also. can you explain how should I have to connect my esp8266 with Daly BMS using UART I used three-pin the first 1 is GND 5th is TX and 6th for Rx? Is it okay? and please provide a code for getting all data from BMS.
please help me, sir. I request you.

![serial3](https://user-images.githubusercontent.com/74247546/131110649-b60ae365-a506-4a80-9078-fb11ccde539b.PNG)

**Comment by PRADIPMAHAJAN** [comment]
Can you show your wiring diagram of Daly BMS with arduino please

**Comment by maland16** [comment]
I think the issue you're running into is that the Arduino Uno only has one UART peripheral. This means that you can either communicate with a laptop via UART over USB **or** the BMS via UART. You might want to look at using a teensy (that's what I used, this code hasn't been tested on an arduino yet) or possibly move to an arduino variant that has multiple UART peripherals, like an arduino Mega. [See this chart for arduino models & their UART peripherals](https://www.arduino.cc/reference/en/language/functions/communication/serial/):

![image](https://user-images.githubusercontent.com/9269144/132110886-44bc6c84-93e5-4c57-a590-56b8173b0773.png)

**Comment by softwarecrash** [comment]
The ESP82xx have only one full UART Serial port the Serial, the serial1 is only a tx on D4 for debuging.
so you need to change it to Daly_BMS_UART bms(Serial)
