### ISSUE TITLE
Linux port of the library

### ISSUE THREAD

**Issue by tizbac** [maland16/daly-bms-uart#21]
Hi , i made a linux port of your library , soon i will also create an openwrt package to add luci support for monitoring Daly BMS 
You can check it out here, https://github.com/tizbac/daly-bms-uart-linux
Some bits still need to be perfectioned

Sample output of main.cpp

root@OpenWrt:~# ./dalybms2 /dev/ttyUSB0
basic BMS Data:             27.1V2.6I81.4% 
Package Temperature:        8
Highest Cell Voltage Nr:    5 with voltage3.407
Lowest Cell Voltage Nr:     4 with voltage3.393
Number of Cells:            8
Number of Temp Sensors:     1
BMS Chrg / Dischrg Cycles:  152
BMS Heartbeat:              88
Discharge MOSFet Status:    1
Charge MOSFet Status:       1
Remaining Capacity mAh:     16280
root@OpenWrt:~#

**Comment by maland16** [comment]
Awesome! I'll add a link to the readme on this repo to it
